trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
variables:
  buildConfiguration: Release
  usr_docker: samuelsilv
  pswd: samu1705
  
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: ./Employees.UnitTests/Employees.UnitTests.csproj

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: ./Employees.UnitTests/Employees.UnitTests.csproj

  - script: >
      docker build -t employee-api:v$(Build.BuildId) .

      docker tag employee-api:v$(Build.BuildId)
      samuelsilv/employees-project:v$(Build.BuildId)

      docker login -u $(usr_docker) -p $(pswd)

      docker push samuelsilv/employees-project:v$(Build.BuildId)

      docker logout  
