trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
variables:
  buildConfiguration: Release
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: ./Employees.UnitTests/Employees.UnitTests.csproj

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: ./Employees.UnitTests/Employees.UnitTests.csproj

  - script: >
      docker build -t employee-api:$(Build.BuildId) .

      docker tag employee-api:$(Build.BuildId)
      samuelsilv/employees-project:$(Build.BuildId)

      docker login -u $(usr_docker) -p $(pswd)

      docker push samuelsilv/employees-project:$(Build.BuildId)

      docker logout
    # env:
      # usr_docker: samuelsilv
      # pswd: samu1705
